force-app/main/default/objects/Veteran__c/Veteran__c.object-meta.xml
<CustomObject>
    <description>Object to keep track of user information of Veterans</description>
    <label>Veteran</label>
    <nameField>
        <displayFormat>Vet-{00000000}</displayFormat>
        <label>Veteran Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Veterans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Veteran__c/fields/Credit_Score__c.field-meta.xml
<CustomField>
    <fullName>Credit_Score__c</fullName>
    <description>The veteran&apos;s credit score</description>
    <label>Credit Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Veteran__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <description>Date of birth of the Veteran</description>
    <label>Date of Birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Veteran__c/fields/Disability_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Disability_Percentage__c</fullName>
    <description>Level of disability that veteran currently is assigned</description>
    <inlineHelpText>If you currently receive disability please enter the percentage</inlineHelpText>
    <label>Disability Percentage</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Veteran__c/fields/Discharge_Status__c.field-meta.xml
<CustomField>
    <fullName>Discharge_Status__c</fullName>
    <description>What type of discharge did the veteran receive</description>
    <inlineHelpText>Please choose the discharge type you received upon leaving service</inlineHelpText>
    <label>Discharge Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Honorable</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Other Than Honorable</fullName>
            </value>
            <value>
                <fullName>Bad Conduct</fullName>
            </value>
            <value>
                <fullName>Dishonorable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Veteran__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Veteran email</description>
    <inlineHelpText>Please enter your email</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Veteran__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Veteran First Name</description>
    <inlineHelpText>Please enter your first name</inlineHelpText>
    <label>First Name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Veteran__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Veteran Last Name</description>
    <inlineHelpText>Please enter your last name</inlineHelpText>
    <label>Last Name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Veteran__c/fields/Military_Branch__c.field-meta.xml
<CustomField>
    <fullName>Military_Branch__c</fullName>
    <description>Branch of the military that the veteran served in</description>
    <inlineHelpText>Please choose the branch you have served in</inlineHelpText>
    <label>Military Branch</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Air Force</fullName>
            </value>
            <value>
                <fullName>Army</fullName>
            </value>
            <value>
                <fullName>Coast Guard</fullName>
            </value>
            <value>
                <fullName>Marines</fullName>
            </value>
            <value>
                <fullName>Navy</fullName>
            </value>
            <value>
                <fullName>Space Force</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Veteran__c/fields/Military_Service_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Military_Service_End_Date__c</fullName>
    <description>Date that the veteran&apos;s military service ended</description>
    <inlineHelpText>Please choose the date that your military service ended</inlineHelpText>
    <label>Military Service End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Veteran__c/fields/Military_Service_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Military_Service_Start_Date__c</fullName>
    <description>Date when the veteran&apos;s military service started</description>
    <inlineHelpText>Please enter the date your military service started</inlineHelpText>
    <label>Military Service Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Veteran__c/fields/Primary_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_Phone_Number__c</fullName>
    <description>Primary phone number of veteran</description>
    <inlineHelpText>Please enter your primary phone number</inlineHelpText>
    <label>Primary Phone Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Veteran__c/fields/Social_Security_Number__c.field-meta.xml
<CustomField>
    <fullName>Social_Security_Number__c</fullName>
    <description>Veteran Social Security Number</description>
    <inlineHelpText>Please enter your social security number</inlineHelpText>
    <label>Social Security Number</label>
    <length>9</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Veteran__c/fields/Veteran_User__c.field-meta.xml
<CustomField>
    <fullName>Veteran_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The veteran user associated with a veteran record</description>
    <label>Veteran User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Veterans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/getVeteranRecord.cls
public with sharing class getVeteranRecord {
    
    @AuraEnabled(cacheable=true)
    public static Veteran__c getVeteranInfo(Id userId){

        Veteran__c veteranInfo;
        try {
            List<Veteran__c> veteranRecords = [SELECT Id, First_Name__c, Last_Name__c, Credit_Score__c, Date_of_Birth__c, Disability_Percentage__c, Discharge_Status__c, Email__c, Military_Branch__c, Military_Service_End_Date__c, Military_Service_Start_Date__c, Social_Security_Number__c, Primary_Phone_Number__c
                            FROM Veteran__c 
                            WHERE Veteran_User__c =: userId];

            if (!veteranRecords.isEmpty()) {
                veteranInfo = veteranRecords[0];
            } else {
                veteranInfo = new Veteran__c();
            }
        } catch (Exception e) {
            throw new AuraHandledException('Unable to retrieve Veteran Record ' + e.getMessage());
        }
        return veteranInfo;
    }
}